version: '3.8'

services:

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "8082:80"
      - "2003:2003"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

  nagios:
    image: jasonrivers/nagios
    container_name: nagios
    ports:
      - "8083:80"