apiVersion: v1
kind: Service

metadata:
  name: tamilnadu-tourism-service

spec:
  type: NodePort

  selector:
    app: tamilnadu-tourism

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080